sudo: false
dist: trusty

language: php

cache:
  directories:
    - "$HOME/.composer/cache/files"

matrix:
  include:
    - php: 7.2
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.3
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"
        - PHPSTAN=true

before_install:
  - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update $COMPOSER_FLAGS

script:
  - if [[ $PHPSTAN = true ]]; then composer phpstan; fi
  - composer phpunit
